{
 "title": "Infrastructure Node View",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "nodes",
    "query": "label_values(collectd_cpu_percent, host)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Global Alerts",
   "type": "table-old",
   "description": "Show currently firing alerts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "Recent Global Alerts",
   "type": "table-old",
   "description": "Show recently fired alerts in 5m time steps",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  { "title": "Quickview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "absent({host = '$hosts'}) or label_replace(vector(0), \"host\", \"$hosts\", \"host\", \".*\")"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time node has been operational",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_uptime{host=\"$hosts\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_cpu_percent{type_instance!=\"idle\", host=\"$hosts\"}) / count(sum by (plugin_instance) (collectd_cpu_percent{host=\"$hosts\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_memory{type_instance=\"used\",host=\"$hosts\"})/ sum(collectd_memory{host=\"$hosts\"})",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "File Systems",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(collectd_df_df_complex{host=\"$hosts\",type_instance=\"used\"}) by (plugin_instance) / sum(collectd_df_df_complex{host=\"$hosts\"}) by (plugin_instance)",
     "legendFormat": "{{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(collectd_interface_if_errors_rx_total{host=\"$hosts\"}) + sum(collectd_interface_if_errors_tx_total{host=\"$hosts\"})",
     "legendFormat": "{{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "Load average represents the average number of running and un-interruptable processes residing in the kernel's execution queue. \n\nTypically, short term, midterm, and long term series give running averages of 1m, 5m, and 15m, respectively. ",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "collectd_load_shortterm{host=\"$hosts\"}",
     "legendFormat": "short term"
    },
    {
     "expr": "collectd_load_midterm{host=\"$hosts\"}",
     "legendFormat": "mid term"
    },
    {
     "expr": "collectd_load_longterm{host=\"$hosts\"}",
     "legendFormat": "long term"
    }
   ]
  },
  { "title": "Network Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_octets_rx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Rx {{plugin_instance}}"
    },
    {
     "expr": "rate(collectd_interface_if_octets_tx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Tx {{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "errors/s" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_errors_rx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Rx {{plugin_instance}}"
    },
    {
     "expr": "rate(collectd_interface_if_errors_tx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Tx {{plugin_instance}}"
    }
   ]
  },
  {
   "title": "Drop Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(collectd_interface_if_dropped_rx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Rx {{plugin_instance}}"
    },
    {
     "expr": "rate(collectd_interface_if_dropped_tx_total{host=\"$hosts\"}[10m])",
     "legendFormat": "Tx {{plugin_instance}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Aggr. Usage",
   "type": "graph",
   "description": "Average non-idle CPU activity of all cores on node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_cpu_percent{type_instance!=\"idle\", host=\"$hosts\"}) / count(sum by (plugin_instance) (collectd_cpu_percent{host=\"$hosts\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Aggr. Usage by Type",
   "type": "graph",
   "description": "Shows average time spent for each activity across all cores",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_cpu_percent{type_instance!=\"idle\", host=\"$hosts\"}) by (type_instance) / count(collectd_cpu_percent{host=\"$hosts\"}) by (type_instance)",
     "legendFormat": "{{type_instance}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory used on node",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_memory{type_instance=\"used\",host=\"$hosts\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Huge Pages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_hugepages_vmpage_number{type_instance=\"used\",host=\"$hosts\"})",
     "legendFormat": "{{hugepages}}"
    }
   ]
  },
  {
   "title": "Huge Pages (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(collectd_hugepages_vmpage_number{type_instance=\"used\",host=\"$hosts\"}) / sum(collectd_hugepages_vmpage_number{host=\"$hosts\"})",
     "legendFormat": "{{hugepages}}"
    }
   ]
  },
  { "title": "File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Inode Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (plugin_instance) (collectd_df_df_inodes{type_instance=\"used\", host=\"$hosts\"}) / sum by (plugin_instance) (collectd_df_df_inodes{host=\"$hosts\"})",
     "legendFormat": "{{plugin_instance}}"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (plugin_instance) (collectd_df_df_complex{type_instance!~\"free\",host=\"$hosts\"})",
     "legendFormat": "{{plugin_instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Traffic",
   "type": "graph",
   "description": "10m rolling average",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_octets_read_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_octets_write_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "Approximate percentage of total disk bandwidth being used.\n\nWeighted I/O includes the backlog that may be accumulating.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_io_time_io_time_total{host=\"$hosts\"}[1h]))/1000",
     "legendFormat": "i/o"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_io_time_weighted_io_time_total{host=\"$hosts\"}[1h]))/1000",
     "legendFormat": "weighted i/o"
    }
   ]
  },
  {
   "title": "Operations/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_ops_read_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_ops_write_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Avg. I/O Operation Time",
   "type": "graph",
   "description": "Average time each I/O operation took to complete. Per the collectd disk plugin docs (https://collectd.org/wiki/index.php/Plugin:Disk), this average is not very accurate.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(collectd_disk_disk_time_read_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(collectd_disk_disk_time_write_total{host=\"$hosts\"}[10m]))",
     "legendFormat": "write"
    }
   ]
  }
 ]
}